services:
  fcp-fd-ingress:
    build:
      context: .
      target: production
    image: fcp-fd-ingress
    container_name: fcp-fd-ingress
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-ingress-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
