# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-ingress:
    build:
      target: development
    image: fcp-fd-ingress-development
    container_name: fcp-fd-ingress-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
