apiVersion: v2
description: Mergeable ingress types root for the Single Front Door.
name: fcp-fd-ingress
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
